<?php
declare(strict_types=1);
require __DIR__.'/auth.php';requireAdmin();require ROOT_PATH.'/includes/books.php';
$db=database();$id=(int)($_GET['id']??0);$book=$id?findBookById($id):null;
$book=$book?:['title'=>'','slug'=>'','subtitle'=>'','description'=>'','cover_image'=>'assets/images/book-cover.png','purchase_url'=>'','format_details'=>'','published_year'=>date('Y'),'display_order'=>10,'status'=>'draft'];
$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 verifyCsrf();$values=['title'=>trim((string)$_POST['title']),'slug'=>trim((string)$_POST['slug']),'subtitle'=>trim((string)$_POST['subtitle']),'description'=>trim((string)$_POST['description']),'cover_image'=>trim((string)$_POST['cover_image']),'purchase_url'=>trim((string)$_POST['purchase_url']),'format_details'=>trim((string)$_POST['format_details']),'published_year'=>(int)$_POST['published_year'],'display_order'=>(int)$_POST['display_order'],'status'=>in_array($_POST['status'],['draft','published','archived'],true)?$_POST['status']:'draft'];
 if(!$values['title']||!preg_match('/^[a-z0-9-]+$/',$values['slug'])){$error='A title and lowercase URL slug are required.';}else{try{if($id){$sql='UPDATE wts_books SET title=:title,slug=:slug,subtitle=:subtitle,description=:description,cover_image=:cover_image,purchase_url=:purchase_url,format_details=:format_details,published_year=:published_year,display_order=:display_order,status=:status WHERE id=:id';$values['id']=$id;}else{$sql='INSERT INTO wts_books (title,slug,subtitle,description,cover_image,purchase_url,format_details,published_year,display_order,status) VALUES (:title,:slug,:subtitle,:description,:cover_image,:purchase_url,:format_details,:published_year,:display_order,:status)';}$db->prepare($sql)->execute($values);header('Location:'.url('admin/books.php?saved=1'));exit;}catch(PDOException $exception){$error='Unable to save. Make sure the slug is unique.';}$book=array_merge($book,$values);}
}
$adminTitle=$id?'Edit publication':'Add publication';require __DIR__.'/_header.php';
?>
<header class="admin-title"><div><p class="kicker">Publication editor</p><h1><?=e($adminTitle)?></h1></div></header>
<section class="admin-panel admin-form"><?php if($error):?><p class="notice error"><?=e($error)?></p><?php endif;?><form method="post"><input type="hidden" name="csrf" value="<?=csrfToken()?>"><div class="admin-form-grid"><label>Title<input name="title" value="<?=e($book['title'])?>" required></label><label>URL slug<input name="slug" value="<?=e($book['slug'])?>" placeholder="the-spirit-of-truth" required></label></div><label>Subtitle<input name="subtitle" value="<?=e($book['subtitle'])?>"></label><label>Description<textarea name="description" rows="6"><?=e($book['description'])?></textarea></label><div class="admin-form-grid"><label>Cover image path<input name="cover_image" value="<?=e($book['cover_image'])?>"></label><label>Purchase URL<input type="url" name="purchase_url" value="<?=e($book['purchase_url'])?>"></label></div><div class="admin-form-grid three"><label>Formats<input name="format_details" value="<?=e($book['format_details'])?>"></label><label>Publication year<input type="number" name="published_year" value="<?=e((string)$book['published_year'])?>"></label><label>Display order<input type="number" name="display_order" value="<?=e((string)$book['display_order'])?>"></label></div><label>Status<select name="status"><?php foreach(['draft','published','archived'] as $status):?><option value="<?=$status?>" <?=$book['status']===$status?'selected':''?>><?=ucfirst($status)?></option><?php endforeach;?></select></label><div class="button-row"><button class="button button-primary">Save publication</button><a class="button button-outline" href="<?=url('admin/books.php')?>">Cancel</a></div></form></section>
<?php require __DIR__.'/_footer.php'; ?>
