<?php
declare(strict_types=1);
require __DIR__ . '/auth.php'; requireAdmin(); require ROOT_PATH . '/includes/mailer.php';
$db=database();$legacy=databaseUsesLegacySchema();$notice='';$error='';
$posts=$legacy?$db->query('SELECT id,title,slug,excerpt,date FROM posts WHERE published=1 ORDER BY date DESC')->fetchAll():$db->query("SELECT id,title,slug,excerpt,published_at AS date FROM wts_posts WHERE status='published' ORDER BY published_at DESC")->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'){
  verifyCsrf();$postId=(int)($_POST['post_id']??0);$post=null;foreach($posts as $candidate)if((int)$candidate['id']===$postId)$post=$candidate;
  if(!$post||!isset($_POST['confirm_send']))$error='Choose a published reflection and confirm the send.';elseif(!smtpConfigured())$error='SMTP is not configured. Save working SMTP settings before sending a campaign.';else{
    $recipients=$legacy?$db->query("SELECT id,email FROM email_subscribers WHERE status='active'")->fetchAll():$db->query("SELECT id,email FROM wts_subscribers WHERE status='active'")->fetchAll();$sent=0;$failed=0;
    foreach($recipients as $recipient){$token=bin2hex(random_bytes(32));try{if($legacy)$db->prepare('UPDATE email_subscribers SET unsubscribe_token_hash=? WHERE id=?')->execute([hash('sha256',$token),$recipient['id']]);else $db->prepare('UPDATE wts_subscribers SET token=? WHERE id=?')->execute([hash('sha256',$token),$recipient['id']]);$postUrl=applicationUrl('blog/post.php?slug='.rawurlencode($post['slug']));$unsubscribeUrl=applicationUrl('unsubscribe.php?id='.rawurlencode((string)$recipient['id']).'&token='.rawurlencode($token));$html='<p>A new reflection is available from Word Truth Spirit.</p><h2>'.e($post['title']).'</h2><p>'.e($post['excerpt']?:'Read the latest reflection on Scripture, truth, and life in the Spirit.').'</p><p><a href="'.e($postUrl).'">Read the reflection</a></p><hr><p style="font-size:12px">You are receiving this because you subscribed to Word Truth Spirit. <a href="'.e($unsubscribeUrl).'">Unsubscribe</a></p>';if(smtpSend($recipient['email'],$post['title'].' | Word Truth Spirit',$html))$sent++;else $failed++;}catch(Throwable $exception){$failed++;}}
    if($legacy&&databaseTableExists('notification_campaigns'))$db->prepare('INSERT INTO notification_campaigns (id,post_id,channel,sent_count,failed_count) VALUES (?,?,?,?,?)')->execute([uuidV4(),$postId,'email',$sent,$failed]);
    $notice="Campaign complete: {$sent} delivered, {$failed} failed.";
  }
}
$history=$legacy&&databaseTableExists('notification_campaigns')?$db->query("SELECT n.sent_count,n.failed_count,n.created_at,p.title FROM notification_campaigns n LEFT JOIN posts p ON p.id=n.post_id WHERE n.channel='email' ORDER BY n.created_at DESC LIMIT 12")->fetchAll():[];
$adminTitle='Email campaigns';$currentAdminPage='campaigns';require __DIR__.'/_header.php';
?>
<header class="admin-title"><div><p class="kicker">Reader updates</p><h1>Email campaigns</h1><p>Send a published reflection to confirmed subscribers, with a secure unsubscribe link added to every message.</p></div></header>
<?php if($notice):?><p class="notice success"><?=e($notice)?></p><?php endif;?><?php if($error):?><p class="notice error"><?=e($error)?></p><?php endif;?>
<section class="admin-panel campaign-panel"><form method="post" onsubmit="return confirm('Send this campaign to every active subscriber?')"><input type="hidden" name="csrf" value="<?=csrfToken()?>"><label>Published reflection<select name="post_id" required><option value="">Select a reflection…</option><?php foreach($posts as $post):?><option value="<?= (int)$post['id'] ?>"><?=e($post['title'])?> · <?=date('M j, Y',strtotime($post['date']))?></option><?php endforeach;?></select></label><p>The email uses the reflection’s title and excerpt, links to the public post, and includes a fresh unsubscribe link for every recipient.</p><label class="toggle-label"><input type="checkbox" name="confirm_send" value="1" required> I am ready to send this to all active subscribers.</label><button class="button button-primary">Send campaign</button></form></section>
<?php if($history):?><section class="admin-panel campaign-history"><h2>Recent delivery history</h2><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Reflection</th><th>Delivered</th><th>Failed</th><th>Sent</th></tr></thead><tbody><?php foreach($history as $item):?><tr><td><?=e($item['title']?:'Archived reflection')?></td><td><?= (int)$item['sent_count']?></td><td><?= (int)$item['failed_count']?></td><td><?=date('M j, Y g:i a',strtotime($item['created_at']))?></td></tr><?php endforeach;?></tbody></table></div></section><?php endif;?>
<?php require __DIR__.'/_footer.php'; ?>
