<?php
declare(strict_types=1);
require __DIR__.'/auth.php';requireAdmin();require ROOT_PATH.'/includes/content.php';
$pages=['home'=>['Home hero','✦ Word Truth Spirit','Where Scripture and Spirit belong together.','Clear biblical teaching for believers who value the authority of God’s Word and the active ministry of the Holy Spirit.'],'foundation'=>['Foundation section','✦ Explore the foundation','One faith. Three essential themes.',''],'word'=>['Word page','✦ Word Truth Spirit','Word','The eternal Word of God is a lamp unto our feet and a light unto our path, guiding believers in truth and wisdom.'],'truth'=>['Truth page','✦ Word Truth Spirit','Truth','Truth is not determined by popular opinion, cultural trends, or human reasoning, but by the eternal and infallible Word of God.'],'spirit'=>['Spirit page','✦ Word Truth Spirit','Spirit','The Holy Spirit is the third person of the Trinity, co-equal and co-eternal with the Father and the Son—not merely an influence, but a divine Person.'],'publications'=>['Publications','✦ Books by Patrick E. Pennington','Publications','Scripture-grounded books written to bring biblical authority and the continuing work of the Holy Spirit into one faithful conversation.'],'commitments'=>['Commitments','✦ Our commitments','Standing firm in biblical integrity.','We invite every reader to receive the Word with readiness of mind and search the Scriptures carefully.'],'contact'=>['Contact','✦ Connect','Contact','Get in touch with questions, comments, or ministry inquiries.'],'blog'=>['Journal','✦ Word Truth Spirit Journal','Letters for a faith that lives beyond Sunday.','Scripture-rooted teaching, honest questions, and practical encouragement from the desk of Patrick E. Pennington.']];
$key=array_key_exists($_GET['page']??'', $pages)?$_GET['page']:'home';$defaults=['kicker'=>$pages[$key][1],'heading'=>$pages[$key][2],'lead'=>$pages[$key][3]];$content=pageContent($key,$defaults);$saved=false;
if($_SERVER['REQUEST_METHOD']==='POST'){verifyCsrf();$key=array_key_exists($_POST['key']??'', $pages)?$_POST['key']:'home';$content=['kicker'=>trim((string)$_POST['kicker']),'heading'=>trim((string)$_POST['heading']),'lead'=>trim((string)$_POST['lead'])];$saved=savePageContent($key,$content);}
$adminTitle='Page content';$currentAdminPage='content';require __DIR__.'/_header.php';?>
<header class="admin-title"><div><p class="kicker">Public website</p><h1>Page content</h1><p>Change main headings, eyebrows, and intro copy without editing code.</p></div></header>
<?php if($saved):?><p class="notice success">Page content saved.</p><?php endif;?><section class="admin-panel admin-form"><form method="post"><input type="hidden" name="csrf" value="<?=csrfToken()?>"><label>Page<select name="key" onchange="location.search='?page='+this.value"><?php foreach($pages as $id=>$page):?><option value="<?=e($id)?>" <?=$key===$id?'selected':''?>><?=e($page[0])?></option><?php endforeach;?></select></label><label>Eyebrow / kicker<input name="kicker" value="<?=e($content['kicker'])?>"></label><label>Main heading<input name="heading" value="<?=e($content['heading'])?>" required></label><label>Introduction<textarea name="lead" rows="5"><?=e($content['lead'])?></textarea></label><button class="button button-primary">Save page content</button></form></section>
<?php require __DIR__.'/_footer.php'; ?>
