<?php
declare(strict_types=1);
require __DIR__ . '/auth.php'; requireAdmin();
$db = database(); $legacy = databaseUsesLegacySchema();
if (!$legacy) { $adminTitle='Conversations'; $currentAdminPage='conversations'; require __DIR__.'/_header.php'; echo '<header class="admin-title"><div><p class="kicker">Reader chat</p><h1>Conversations</h1></div></header><section class="admin-panel empty-state"><span>◌</span><h2>Available with the original database</h2><p>Import 127_0_0_1.sql to manage the Node-site chat conversations here.</p></section>'; require __DIR__.'/_footer.php'; exit; }
if ($_SERVER['REQUEST_METHOD'] === 'POST') { verifyCsrf(); $conversationId=(string)($_POST['conversation_id']??''); $reply=trim((string)($_POST['reply']??'')); if($conversationId!==''&&$reply!==''){ $db->prepare('INSERT INTO chat_messages (id,conversation_id,sender,message) VALUES (?,?,"admin",?)')->execute([uuidV4(),$conversationId,$reply]); $db->prepare('UPDATE chat_conversations SET unread_by_admin=0,last_message_at=CURRENT_TIMESTAMP WHERE id=?')->execute([$conversationId]); } header('Location:'.url('admin/conversations.php?conversation='.urlencode($conversationId))); exit; }
$selected=(string)($_GET['conversation']??''); $conversations=$db->query('SELECT id,name,email,status,page_path,unread_by_admin,last_message_at,created_at FROM chat_conversations ORDER BY last_message_at DESC')->fetchAll(); if(!$selected&&$conversations)$selected=$conversations[0]['id']; $messages=[]; if($selected){$statement=$db->prepare('SELECT sender,message,created_at FROM chat_messages WHERE conversation_id=? ORDER BY created_at');$statement->execute([$selected]);$messages=$statement->fetchAll();}
$current=null; foreach($conversations as $conversation)if($conversation['id']===$selected)$current=$conversation; $adminTitle='Conversations';$currentAdminPage='conversations';require __DIR__.'/_header.php';
?>
<header class="admin-title"><div><p class="kicker">Reader chat</p><h1>Conversations</h1><p>Continue conversations started through the original live chat.</p></div></header>
<section class="inbox-layout"><div class="admin-panel inbox-list"><?php foreach($conversations as $conversation):?><a class="inbox-item <?= $selected===$conversation['id']?'active':'' ?> <?= $conversation['unread_by_admin']?'unread':'' ?>" href="<?=url('admin/conversations.php?conversation='.urlencode($conversation['id']))?>"><strong><?=e($conversation['name'])?></strong><span><?=e($conversation['status'])?> · <?=e($conversation['page_path']?:'/')?></span><small><?=date('M j, Y',strtotime($conversation['last_message_at']))?></small></a><?php endforeach;?></div><article class="admin-panel message-detail"><?php if(!$current):?><div class="empty-state"><span>◌</span><h2>Select a conversation</h2></div><?php else:?><p class="kicker"><?=e($current['status'])?></p><h2><?=e($current['name'])?></h2><p><a href="mailto:<?=e($current['email'])?>"><?=e($current['email'])?></a></p><div class="chat-thread"><?php foreach($messages as $message):?><div class="chat-message <?=e($message['sender'])?>"><span><?=e($message['sender'])?></span><p><?=nl2br(e($message['message']))?></p><small><?=date('M j, g:i a',strtotime($message['created_at']))?></small></div><?php endforeach;?></div><form method="post" class="chat-reply"><input type="hidden" name="csrf" value="<?=csrfToken()?>"><input type="hidden" name="conversation_id" value="<?=e($current['id'])?>"><label>Reply<textarea name="reply" rows="4" required placeholder="Write a response…"></textarea></label><button class="button button-primary">Send reply</button></form><?php endif;?></article></section>
<?php require __DIR__ . '/_footer.php'; ?>
