<?php
declare(strict_types=1);
require __DIR__.'/auth.php';requireAdmin();require ROOT_PATH.'/includes/books.php';require ROOT_PATH.'/includes/analytics.php';require ROOT_PATH.'/includes/products.php';
$db=database();
$bookCount=databaseTableExists('wts_books')?(int)$db->query('SELECT COUNT(*) FROM wts_books')->fetchColumn():count(fallbackBooks());
$postCount=(int)$db->query(databaseUsesLegacySchema()?'SELECT COUNT(*) FROM posts':'SELECT COUNT(*) FROM wts_posts')->fetchColumn();
$messageCount=(int)$db->query(databaseUsesLegacySchema()?'SELECT COUNT(*) FROM contact_messages WHERE is_read=0':"SELECT COUNT(*) FROM wts_contact_messages WHERE status='new'")->fetchColumn();
$productCount=productsAvailable()?(int)$db->query("SELECT COUNT(*) FROM wts_products WHERE status='published'")->fetchColumn():0;
$analytics=analyticsSummary(30); $dailyValues=array_column($analytics['daily'],'total'); $chartMax=max(1,...($dailyValues?:[1]));
$adminTitle='Dashboard';$currentAdminPage='dashboard';require __DIR__.'/_header.php';
?>
<header class="admin-title"><div><p class="kicker">Welcome back</p><h1><?=e($_SESSION['wts_admin_name']??'Administrator')?></h1></div></header>
<section class="admin-stats admin-stats-four"><a href="<?=url('admin/posts.php')?>"><strong><?=$postCount?></strong><span>Blog entries</span></a><a href="<?=url('admin/books.php')?>"><strong><?=$bookCount?></strong><span>Publications</span></a><a href="<?=url('admin/products.php')?>"><strong><?=$productCount?></strong><span>Live products</span></a><a href="<?=url('admin/inbox.php')?>"><strong><?=$messageCount?></strong><span>New messages</span></a></section>
<section class="admin-panel dashboard-actions"><div><p class="kicker">Quick start</p><h2>Keep the ministry moving.</h2><p>Publish a reflection, offer a new resource, or respond to readers from one secure workspace.</p></div><div class="button-row"><a class="button button-primary" href="<?=url('admin/post-edit.php')?>">Write reflection</a><a class="button button-outline" href="<?=url('admin/product-edit.php')?>">Add product</a><a class="button button-outline" href="<?=url('admin/inbox.php')?>">Open inbox</a></div></section>
<section class="analytics-dashboard"><header><div><p class="kicker">First-party analytics</p><h2>Audience activity</h2><p>Last 30 days · privacy-conscious counts without storing IP addresses.</p></div><a class="button button-outline" href="<?=url('admin/seo.php')?>">Open SEO studio</a></header><div class="analytics-kpis"><div><strong><?=$analytics['views']?></strong><span>Page views</span></div><div><strong><?=$analytics['visitors']?></strong><span>Unique daily visitors</span></div><div><strong><?=$analytics['engagedReaders']?></strong><span>Engaged blog readers</span></div><div><strong><?=$analytics['averageScroll']?>%</strong><span>Average scroll depth</span></div><div><strong><?=$analytics['completionRate']?>%</strong><span>Read to 90%+</span></div></div><div class="analytics-grid"><section class="admin-panel traffic-chart"><h3>Traffic trend</h3><div class="bar-chart"><?php foreach($analytics['daily'] as $day):?><span title="<?=e($day['viewed_on'])?>: <?=$day['total']?> views" style="height:<?=max(5,round(((int)$day['total']/$chartMax)*100))?>%"></span><?php endforeach;?><?php if(!$analytics['daily']):?><p>No visits have been recorded yet. Public page views will appear here as readers browse the site.</p><?php endif;?></div></section><section class="admin-panel analytics-list"><h3>Top pages</h3><?php foreach($analytics['topPages'] as $item):?><p><span><?=e($item['page_path'])?></span><strong><?=$item['total']?></strong></p><?php endforeach;?><?php if(!$analytics['topPages']):?><p>No page data yet.</p><?php endif;?></section><section class="admin-panel analytics-list"><h3>Top referrers</h3><?php foreach($analytics['referrers'] as $item):?><p><span><?=e($item['referrer_host'])?></span><strong><?=$item['total']?></strong></p><?php endforeach;?><?php if(!$analytics['referrers']):?><p>Direct traffic or no referrer data yet.</p><?php endif;?></section></div><section class="admin-panel analytics-list analytics-posts"><h3>Reflection engagement</h3><?php foreach($analytics['topPosts'] as $item):?><p><span>/<?=e($item['post_slug'])?><small><?=$item['readers']?> readers · <?=$item['average_seconds']?>s active</small></span><strong><?=$item['average_scroll']?>% scroll · <?=$item['completion_rate']?>% read</strong></p><?php endforeach;?><?php if(!$analytics['topPosts']):?><p>Engagement will appear after readers scroll through published reflections.</p><?php endif;?></section></section>
<?php require __DIR__.'/_footer.php'; ?>
