<?php
declare(strict_types=1);
require __DIR__.'/auth.php';requireAdmin();
require ROOT_PATH.'/includes/comments.php';
$db=database();$legacy=databaseUsesLegacySchema();if($_SERVER['REQUEST_METHOD']==='POST'){verifyCsrf();$db->prepare('DELETE FROM '.($legacy?'posts':'wts_posts').' WHERE id=?')->execute([(int)$_POST['id']]);header('Location:'.url('admin/posts.php?deleted=1'));exit;}
$posts=$legacy
 ?$db->query("SELECT id,title,slug,category,IF(published=2,'update',IF(published=1,'published','draft')) AS status,date AS published_at FROM posts ORDER BY date DESC,created_at DESC")->fetchAll()
 :$db->query('SELECT id,title,slug,category,status,published_at FROM wts_posts ORDER BY published_at DESC,created_at DESC')->fetchAll();
$allPosts=$posts;$statusFilter=in_array($_GET['status']??'', ['all','published','draft','archived','update'],true)?(string)$_GET['status']:'all';$search=mb_strtolower(trim((string)($_GET['q']??'')));
$posts=array_values(array_filter($posts,function(array $post)use($statusFilter,$search):bool{return ($statusFilter==='all'||$post['status']===$statusFilter)&&($search===''||str_contains(mb_strtolower($post['title'].' '.$post['slug'].' '.$post['category']),$search));}));
$postCounts=['all'=>count($allPosts),'published'=>0,'draft'=>0,'archived'=>0,'update'=>0];foreach($allPosts as $row)if(isset($postCounts[$row['status']]))$postCounts[$row['status']]++;
$commentCounts=[];if(ensureCommentsTable())foreach($db->query("SELECT post_slug,COUNT(*) AS total FROM wts_blog_comments WHERE status='approved' GROUP BY post_slug")->fetchAll() as $row)$commentCounts[$row['post_slug']]=(int)$row['total'];
$adminTitle='Journal';$currentAdminPage='posts';require __DIR__.'/_header.php';
?>
<header class="admin-title"><div><p class="kicker">Content</p><h1>Journal</h1><p>Write, organize, publish, and follow the reader conversation from one workspace.</p></div><a class="button button-primary" href="<?=url('admin/post-edit.php')?>">New reflection</a></header>
<section class="journal-admin-stats"><?php foreach(['all'=>'All reflections','published'=>'Published','draft'=>'Drafts','update'=>'Direct updates'] as $key=>$label):?><a class="<?=$statusFilter===$key?'active':''?>" href="<?=url('admin/posts.php?status='.$key)?>"><strong><?=$postCounts[$key]?></strong><span><?=$label?></span></a><?php endforeach;?></section>
<section class="admin-panel journal-admin-panel"><form class="journal-admin-toolbar" method="get"><label>Status<select name="status"><?php foreach(['all'=>'All statuses','published'=>'Published','draft'=>'Drafts','update'=>'Direct updates','archived'=>'Archived'] as $key=>$label):?><option value="<?=$key?>" <?=$statusFilter===$key?'selected':''?>><?=$label?></option><?php endforeach;?></select></label><label>Search reflections<input type="search" name="q" value="<?=e((string)($_GET['q']??''))?>" placeholder="Title, category, or URL"></label><button class="button button-outline">Filter</button></form><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Reflection</th><th>Category</th><th>Status</th><th>Discussion</th><th>Published</th><th>Actions</th></tr></thead><tbody><?php foreach($posts as $post):?><tr><td><strong><?=e($post['title'])?></strong><small>/<?=e($post['slug'])?></small></td><td><?=e($post['category'])?></td><td><span class="status-pill status-<?=e($post['status'])?>"><?=e($post['status'])?></span></td><td><a href="<?=url('admin/comments.php?q='.urlencode((string)$post['slug']).'&status=all')?>"><?=(int)($commentCounts[$post['slug']]??0)?> comments</a></td><td><?=e($post['published_at']?date('M j, Y',strtotime($post['published_at'])):'—')?></td><td><a href="<?=url('blog/post.php?slug='.urlencode((string)$post['slug']))?>" target="_blank" rel="noopener">View</a><a href="<?=url('admin/post-edit.php?id='.(int)$post['id'])?>">Edit</a><form method="post" onsubmit="return confirm('Delete this reflection?')"><input type="hidden" name="csrf" value="<?=csrfToken()?>"><input type="hidden" name="id" value="<?=(int)$post['id']?>"><button>Delete</button></form></td></tr><?php endforeach;?></tbody></table></div><?php if(!$posts):?><div class="empty-state"><span>⌕</span><h2>No matching reflections</h2><p>Clear the filters or create a new reflection.</p></div><?php endif;?></section>
<?php require __DIR__.'/_footer.php'; ?>
