<?php
declare(strict_types=1);
require __DIR__.'/auth.php';requireAdmin();
$db=database();$legacy=databaseUsesLegacySchema();$id=(int)($_GET['id']??0);$post=null;if($id){$statement=$db->prepare('SELECT * FROM '.($legacy?'posts':'wts_posts').' WHERE id=?');$statement->execute([$id]);$post=$statement->fetch();if($post&&$legacy){$post['body']=$post['content'];$post['reading_minutes']=(int)$post['read_time'];$post['status']=$post['published']?'published':'draft';$post['published_at']=$post['date'];}}
$post=$post?:['title'=>'','slug'=>'','category'=>'general','excerpt'=>'','body'=>'','author'=>'Patrick E. Pennington','reading_minutes'=>5,'status'=>'draft','published_at'=>date('Y-m-d\TH:i')];$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){verifyCsrf();$values=['title'=>trim((string)$_POST['title']),'slug'=>trim((string)$_POST['slug']),'category'=>trim((string)$_POST['category']),'excerpt'=>trim((string)$_POST['excerpt']),'body'=>trim((string)$_POST['body']),'author'=>trim((string)$_POST['author']),'reading_minutes'=>max(1,(int)$_POST['reading_minutes']),'status'=>in_array($_POST['status'],['draft','published','archived'],true)?$_POST['status']:'draft','published_at'=>$_POST['published_at']?date('Y-m-d H:i:s',strtotime($_POST['published_at'])):null];if(!$values['title']||!preg_match('/^[a-z0-9-]+$/',$values['slug'])||!$values['body']){$error='Title, URL slug, and article content are required.';}else{try{if($legacy){$legacyValues=['title'=>$values['title'],'slug'=>$values['slug'],'category'=>$values['category'],'excerpt'=>$values['excerpt'],'content'=>$values['body'],'author'=>$values['author'],'read_time'=>$values['reading_minutes'].' min read','published'=>$values['status']==='published'?1:0,'date'=>$values['published_at']?date('Y-m-d',strtotime($values['published_at'])):null];if($id){$sql='UPDATE posts SET title=:title,slug=:slug,category=:category,excerpt=:excerpt,content=:content,author=:author,read_time=:read_time,published=:published,date=:date WHERE id=:id';$legacyValues['id']=$id;}else{$sql='INSERT INTO posts (title,slug,category,excerpt,content,author,read_time,published,date) VALUES (:title,:slug,:category,:excerpt,:content,:author,:read_time,:published,:date)';}$db->prepare($sql)->execute($legacyValues);}else{if($id){$sql='UPDATE wts_posts SET title=:title,slug=:slug,category=:category,excerpt=:excerpt,body=:body,author=:author,reading_minutes=:reading_minutes,status=:status,published_at=:published_at WHERE id=:id';$values['id']=$id;}else{$sql='INSERT INTO wts_posts (title,slug,category,excerpt,body,author,reading_minutes,status,published_at) VALUES (:title,:slug,:category,:excerpt,:body,:author,:reading_minutes,:status,:published_at)';}$db->prepare($sql)->execute($values);}header('Location:'.url('admin/posts.php?saved=1'));exit;}catch(PDOException $exception){$error='Unable to save. Make sure the slug is unique.';}$post=array_merge($post,$values);}}
$adminTitle=$id?'Edit reflection':'New reflection';require __DIR__.'/_header.php';
?>
<header class="admin-title"><div><p class="kicker">Journal editor</p><h1><?=e($adminTitle)?></h1></div></header><section class="admin-panel admin-form"><?php if($error):?><p class="notice error"><?=e($error)?></p><?php endif;?><form method="post"><input type="hidden" name="csrf" value="<?=csrfToken()?>"><div class="admin-form-grid"><label>Title<input name="title" value="<?=e($post['title'])?>" required></label><label>URL slug<input name="slug" value="<?=e($post['slug'])?>" required></label></div><div class="admin-form-grid three"><label>Category<select name="category"><?php foreach(['word','truth','spirit','general','christmas'] as $category):?><option <?=$post['category']===$category?'selected':''?>><?=$category?></option><?php endforeach;?></select></label><label>Reading minutes<input type="number" min="1" name="reading_minutes" value="<?=(int)$post['reading_minutes']?>"></label><label>Author<input name="author" value="<?=e($post['author'])?>"></label></div><label>Excerpt<textarea name="excerpt" rows="3"><?=e($post['excerpt'])?></textarea></label><label>Article content<textarea class="article-editor" name="body" rows="18" required><?=e($post['body'])?></textarea></label><div class="admin-form-grid"><label>Publish date<input type="datetime-local" name="published_at" value="<?=e($post['published_at']?date('Y-m-d\TH:i',strtotime($post['published_at'])):'')?>"></label><label>Status<select name="status"><?php foreach(['draft','published','archived'] as $status):?><option value="<?=$status?>" <?=$post['status']===$status?'selected':''?>><?=ucfirst($status)?></option><?php endforeach;?></select></label></div><div class="button-row"><button class="button button-primary">Save reflection</button><a class="button button-outline" href="<?=url('admin/posts.php')?>">Cancel</a></div></form></section>
<?php require __DIR__.'/_footer.php'; ?>
