<?php
declare(strict_types=1);
require __DIR__ . '/auth.php'; requireAdmin(); require ROOT_PATH . '/includes/seo.php';
$pages=['home'=>['Home','/'],'word'=>['Word','/word.php'],'truth'=>['Truth','/truth.php'],'spirit'=>['Spirit','/spirit.php'],'publications'=>['Publications','/publications.php'],'blog'=>['Blog','/blog/'],'commitments'=>['Commitments','/commitments.php'],'contact'=>['Contact','/contact.php']];
$key=array_key_exists($_GET['page']??'', $pages)?$_GET['page']:'home'; ensureSeoTable(); $saved=false;$error='';
if($_SERVER['REQUEST_METHOD']==='POST') { verifyCsrf(); $key=array_key_exists($_POST['page_key']??'', $pages)?$_POST['page_key']:'home'; try { database()->prepare('INSERT INTO wts_seo_pages (page_key,meta_title,meta_description,focus_keyword) VALUES (?,?,?,?) ON DUPLICATE KEY UPDATE meta_title=VALUES(meta_title),meta_description=VALUES(meta_description),focus_keyword=VALUES(focus_keyword)')->execute([$key,trim((string)$_POST['meta_title']),trim((string)$_POST['meta_description']),trim((string)$_POST['focus_keyword'])]); $saved=true; } catch(PDOException $e) {$error='Could not save SEO settings.';} }
$seo=seoPage($key); $seo=array_merge(['meta_title'=>$pages[$key][0].' | Word Truth Spirit','meta_description'=>'Biblical teaching where Scripture and Spirit belong together.','focus_keyword'=>''], $seo);
$adminTitle='SEO studio';$currentAdminPage='seo';require __DIR__.'/_header.php';
?>
<header class="admin-title"><div><p class="kicker">Search visibility</p><h1>SEO studio</h1><p>See how each public page can appear in Google, improve the on-page score, and save the title and description that visitors will see.</p></div></header>
<?php if($error):?><p class="notice error"><?=e($error)?></p><?php elseif($saved):?><p class="notice success">SEO details saved for <?=e($pages[$key][0])?>.</p><?php endif;?>
<div class="seo-layout"><section class="admin-panel seo-form"><form method="post" data-seo-form><input type="hidden" name="csrf" value="<?=csrfToken()?>"><label>Page<select name="page_key" data-seo-page><?php foreach($pages as $pageKey=>[$name,$path]):?><option value="<?=e($pageKey)?>" <?=$key===$pageKey?'selected':''?>><?=e($name)?></option><?php endforeach;?></select></label><label>SEO title <small><span data-title-count>0</span>/60 recommended</small><input name="meta_title" maxlength="500" data-seo-title value="<?=e($seo['meta_title'])?>"></label><label>Meta description <small><span data-description-count>0</span>/160 recommended</small><textarea name="meta_description" rows="5" maxlength="1000" data-seo-description><?=e($seo['meta_description'])?></textarea></label><label>Focus keyword<input name="focus_keyword" data-seo-keyword value="<?=e($seo['focus_keyword'])?>" placeholder="biblical truth"></label><button class="button button-primary">Save SEO details</button></form></section><aside class="seo-sidebar"><section class="admin-panel seo-score"><p class="kicker">Content check</p><strong data-seo-score>0</strong><span>/100 SEO score</span><ul data-seo-checks></ul></section><section class="admin-panel google-preview"><p>Google search preview</p><a data-preview-url>wordtruthspirit.com<?=e($pages[$key][1])?></a><h2 data-preview-title></h2><p data-preview-description></p></section><section class="admin-panel seo-health"><strong>Technical SEO is active</strong><p>Canonical URLs, social previews, article schema, and the XML sitemap are generated automatically.</p><a href="<?=url('sitemap.xml')?>" target="_blank" rel="noopener">View sitemap ↗</a></section><p class="seo-note">Article-specific title and description controls remain in each blog reflection editor.</p></aside></div>
<script>window.wtsSeoPagePath=<?=json_encode($pages[$key][1])?>;</script>
<?php require __DIR__.'/_footer.php'; ?>
