<?php
declare(strict_types=1);
require __DIR__ . '/auth.php'; requireAdmin(); require ROOT_PATH . '/includes/settings.php'; require ROOT_PATH . '/includes/mailer.php';
$error='';$saved=false;$testResult='';$experience=siteExperience();
if($_SERVER['REQUEST_METHOD']==='POST'){
  verifyCsrf();
  $experience=['announcement'=>['enabled'=>isset($_POST['announcement_enabled']),'message'=>trim((string)($_POST['announcement_message']??'')),'actionLabel'=>trim((string)($_POST['announcement_label']??'')),'actionUrl'=>trim((string)($_POST['announcement_url']??'')),'tone'=>'navy'],'popup'=>['enabled'=>isset($_POST['popup_enabled']),'id'=>'welcome','eyebrow'=>trim((string)($_POST['popup_eyebrow']??'')),'title'=>trim((string)($_POST['popup_title']??'')),'body'=>trim((string)($_POST['popup_body']??'')),'actionLabel'=>trim((string)($_POST['popup_label']??'')),'actionUrl'=>trim((string)($_POST['popup_url']??'')),'delaySeconds'=>max(0,min(60,(int)($_POST['popup_delay']??6)))]];
  if(!$experience['announcement']['message']||!$experience['popup']['title'])$error='Enter the required promotion copy.';
  elseif(!setAppSetting('site.experience',json_encode($experience,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE))||!setAppSetting('ministry.donationUrl',trim((string)($_POST['donation_url']??'')))||!setAppSetting('ministry.donationLabel',trim((string)($_POST['donation_label']??'Support the ministry'))))$error='Could not save promotion or ministry giving settings. Confirm the database is connected.';
  else{
    $env=['SMTP_HOST'=>trim((string)($_POST['smtp_host']??'')),'SMTP_PORT'=>trim((string)($_POST['smtp_port']??'465')),'SMTP_USER'=>trim((string)($_POST['smtp_user']??'')),'SMTP_FROM_EMAIL'=>trim((string)($_POST['smtp_from_email']??'')),'SMTP_FROM_NAME'=>trim((string)($_POST['smtp_from_name']??'Word Truth Spirit')),'SMTP_ENCRYPTION'=>trim((string)($_POST['smtp_encryption']??'ssl')),'CONTACT_TO_EMAIL'=>trim((string)($_POST['contact_to_email']??''))];
    if(trim((string)($_POST['smtp_pass']??''))!=='')$env['SMTP_PASS']=(string)$_POST['smtp_pass'];
    if(!updateEnvironment($env))$error='Promotion settings were saved, but the SMTP configuration file could not be updated.';else {
      $saved=true;
      if(($_POST['action']??'save')==='test_smtp'){
        $testEmail=trim((string)($_POST['smtp_test_email']??''));
        if(!filter_var($testEmail,FILTER_VALIDATE_EMAIL))$error='Enter a valid test-recipient email address.';
        elseif(smtpSend($testEmail,'Word Truth Spirit SMTP test','<p>This is a successful SMTP test from the Word Truth Spirit administration workspace.</p><p>If you received this message, the current sender configuration can deliver email.</p>','This is a successful SMTP test from the Word Truth Spirit administration workspace.'))$testResult='Test email sent to '.$testEmail.'.';
        else $error='The SMTP test could not be delivered. Recheck the host, port, encryption, username, password, and sender address.';
      }
    }
  }
}
$adminTitle='Promotions & SMTP';$currentAdminPage='settings';require __DIR__.'/_header.php';
?>
<header class="admin-title"><div><p class="kicker">Site controls</p><h1>Promotions &amp; SMTP</h1><p>Control the announcement, welcome popup, sender identity, and delivery settings used across the public website.</p></div></header>
<form method="post" class="settings-layout"><input type="hidden" name="csrf" value="<?=csrfToken()?>"><?php if($error):?><p class="notice error"><?=e($error)?></p><?php elseif($testResult):?><p class="notice success"><?=e($testResult)?></p><?php elseif($saved):?><p class="notice success">Settings saved. The next page request will use the new promotion and mail configuration.</p><?php endif;?>
<section class="admin-panel settings-section"><h2>Announcement banner</h2><label class="toggle-label"><input type="checkbox" name="announcement_enabled" <?=$experience['announcement']['enabled']?'checked':''?>> Show on the public website</label><label>Message<input name="announcement_message" value="<?=e($experience['announcement']['message'])?>" required></label><div class="admin-form-grid"><label>Button label<input name="announcement_label" value="<?=e($experience['announcement']['actionLabel'])?>"></label><label>Button URL<input name="announcement_url" value="<?=e($experience['announcement']['actionUrl'])?>"></label></div></section>
<section class="admin-panel settings-section"><h2>Welcome popup</h2><label class="toggle-label"><input type="checkbox" name="popup_enabled" <?=$experience['popup']['enabled']?'checked':''?>> Show once per browser session</label><div class="admin-form-grid"><label>Eyebrow<input name="popup_eyebrow" value="<?=e($experience['popup']['eyebrow'])?>"></label><label>Delay in seconds<input type="number" min="0" max="60" name="popup_delay" value="<?= (int)$experience['popup']['delaySeconds']?>"></label></div><label>Title<input name="popup_title" value="<?=e($experience['popup']['title'])?>" required></label><label>Message<textarea name="popup_body" rows="4"><?=e($experience['popup']['body'])?></textarea></label><div class="admin-form-grid"><label>Button label<input name="popup_label" value="<?=e($experience['popup']['actionLabel'])?>"></label><label>Button URL<input name="popup_url" value="<?=e($experience['popup']['actionUrl'])?>"></label></div></section>
<section class="admin-panel settings-section"><h2>Ministry giving</h2><p>Add your PayPal donation link to display a support button in the public footer. Use the full secure PayPal URL.</p><label>PayPal donation URL<input type="url" name="donation_url" value="<?=e((string)appSetting('ministry.donationUrl',''))?>" placeholder="https://www.paypal.com/donate/?hosted_button_id=..."></label><label>Button label<input name="donation_label" value="<?=e((string)appSetting('ministry.donationLabel','Support the ministry'))?>" placeholder="Support the ministry"></label></section>
<section class="admin-panel settings-section"><h2>SMTP delivery</h2><p>Passwords are stored only in <code>.env</code> and are never displayed here. Leave the password empty to keep the existing value.</p><div class="admin-form-grid three"><label>Host<input name="smtp_host" value="<?=e((string)getenv('SMTP_HOST'))?>" placeholder="smtp.example.com"></label><label>Port<input type="number" name="smtp_port" value="<?=e((string)(getenv('SMTP_PORT')?:'465'))?>"></label><label>Encryption<select name="smtp_encryption"><option value="ssl" <?=getenv('SMTP_ENCRYPTION')==='ssl'?'selected':''?>>SSL (465)</option><option value="tls" <?=getenv('SMTP_ENCRYPTION')==='tls'?'selected':''?>>TLS (587)</option><option value="none" <?=getenv('SMTP_ENCRYPTION')==='none'?'selected':''?>>None</option></select></label></div><div class="admin-form-grid"><label>Username<input name="smtp_user" value="<?=e((string)getenv('SMTP_USER'))?>"></label><label>Password<input type="password" name="smtp_pass" placeholder="Leave blank to keep current password"></label></div><div class="admin-form-grid"><label>From email<input type="email" name="smtp_from_email" value="<?=e((string)getenv('SMTP_FROM_EMAIL'))?>"></label><label>From name<input name="smtp_from_name" value="<?=e((string)(getenv('SMTP_FROM_NAME')?:'Word Truth Spirit'))?>"></label></div><label>Contact notification recipient<input type="email" name="contact_to_email" value="<?=e((string)(getenv('CONTACT_TO_EMAIL')?:appSetting('email.contactToEmail','')))?>"></label><div class="smtp-test"><label>Test recipient<input type="email" name="smtp_test_email" placeholder="you@example.com"></label><button class="button button-outline" name="action" value="test_smtp" type="submit">Send SMTP test</button></div></section>
<div class="button-row"><button class="button button-primary" name="action" value="save">Save site controls</button><a class="button button-outline" href="<?=url('admin/')?>">Cancel</a></div></form>
<?php require __DIR__.'/_footer.php'; ?>
