<?php declare(strict_types=1); require dirname(__DIR__).'/includes/bootstrap.php'; require ROOT_PATH.'/includes/members.php';
if(memberLoggedIn()){header('Location:'.url('members/'));exit;} $error='';$sent=false;
if($_SERVER['REQUEST_METHOD']==='POST') { $name=trim((string)($_POST['display_name']??''));$email=filter_var(trim((string)($_POST['email']??'')),FILTER_VALIDATE_EMAIL);$password=(string)($_POST['password']??'');$confirm=(string)($_POST['password_confirm']??'');
  if(!memberVerifyCsrf()||mb_strlen($name)<2||mb_strlen($name)>120||!$email||strlen($password)<12||$password!==$confirm) $error='Use a display name, a valid email, and a matching password of at least 12 characters.';
  elseif(!($db=database())) $error='Accounts are temporarily unavailable.'; else try { $token=bin2hex(random_bytes(32));$db->prepare('INSERT INTO wts_members (display_name,profile_slug,email,password_hash,confirmation_token_hash,confirmation_sent_at) VALUES (?,?,?,?,?,NOW())')->execute([$name,memberSlug($name),$email,password_hash($password,PASSWORD_DEFAULT),hash('sha256',$token)]);$member=['id'=>(int)$db->lastInsertId(),'email'=>$email];$sent=sendMemberConfirmation($member,$token); }
  catch(PDOException $e){$error='An account already exists for that email address. Sign in or request a new confirmation email.';}
}
$pageTitle='Create your account | Word Truth Spirit';$pageDescription='Create a confirmed Word Truth Spirit reader account.';require ROOT_PATH.'/includes/header.php'; ?>
<main class="member-auth-page"><section class="member-auth-card"><p class="kicker">Reader account</p><h1>Create your account</h1><p>Save your profile, connect thoughtful comments to your name, and keep your checkout activity in one place.</p><?php if($error):?><p class="notice error"><?=e($error)?></p><?php elseif($_SERVER['REQUEST_METHOD']==='POST'):?><p class="notice success">Account created. <?= $sent?'Check your inbox to confirm your email before signing in.':'Confirmation email could not be sent yet; contact us for help.' ?></p><?php endif;?><form method="post"><input type="hidden" name="csrf" value="<?=e(memberCsrfToken())?>"><label>Display name<input name="display_name" autocomplete="name" maxlength="120" required value="<?=e((string)($_POST['display_name']??''))?>"></label><label>Email address<input type="email" name="email" autocomplete="email" required value="<?=e((string)($_POST['email']??''))?>"></label><label>Password <small>12 characters minimum</small><input type="password" name="password" autocomplete="new-password" minlength="12" required></label><label>Confirm password<input type="password" name="password_confirm" autocomplete="new-password" minlength="12" required></label><button class="button button-primary">Create account</button></form><p class="member-auth-switch">Already registered? <a href="<?=url('members/login.php')?>">Sign in</a></p></section></main><?php require ROOT_PATH.'/includes/footer.php'; ?>
